module.exports = {
  PORT: process.env.PORT || 3000,

  MONGO_CONNECTION_STRING:
    process.env.MONGO_CONNECTION_STRING || 'mongodb://localhost:27017/cognito',

  NAME: process.env.NAME,
  VERSION: process.env.VERSION,

  REDIS_SERVER: process.env.REDIS_SERVER,
  REDIS_SERVER_PASSWORD: process.env.REDIS_SERVER_PASSWORD,
  REDIS_DATABASE: process.env.REDIS_DATABASE,
  REDIS_PORT: process.env.REDIS_PORT,

  COGNITO_DISCOVERY_ENDPOINT: process.env.COGNITO_DISCOVERY_ENDPOINT,
  APP_AUTH_CODE_CLIENT_ID: process.env.APP_AUTH_CODE_CLIENT_ID,
  APP_AUTH_CODE_CLIENT_SECRET: process.env.APP_AUTH_CODE_CLIENT_SECRET,
  APP_AUTH_CODE_SCOPES: process.env.APP_AUTH_CODE_SCOPES
}
